kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx-haproxy-ingress
spec:
  rules:
    - host: demo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 9009
